import { LightningElement } from 'lwc';
import getStatus from '@salesforce/apex/FieldUsageController.getStatus';
import runNow from '@salesforce/apex/FieldUsageController.runNow';
import saveSchedules from '@salesforce/apex/FieldUsageController.saveSchedules';
import deleteSchedule from '@salesforce/apex/FieldUsageController.deleteSchedule';
import getScheduledJobs from '@salesforce/apex/FieldUsageController.getScheduledJobs';
import pauseSchedule from '@salesforce/apex/FieldUsageController.pauseSchedule';
import resumeSchedule from '@salesforce/apex/FieldUsageController.resumeSchedule';
import getSourceTypes from '@salesforce/apex/FieldUsageController.getSourceTypes';
import getRecentRuns from '@salesforce/apex/FieldUsageController.getRecentRuns';
import getErrorDetail from '@salesforce/apex/FieldUsageErrorController.getErrorDetail';

export default class FieldUsageSettings extends LightningElement {
    status; jobs=[]; sourceTypes=[]; schedules=[]; history=[]; busy=false; message=''; scheduleSeq=0; poller=null; activeRunId=null; expandedRunId=null; errorDetails={}; errorLoadingId=null; displayedProgress=0; progressRunId=null;
    connectedCallback(){this.refresh();this.startPolling();}
    disconnectedCallback(){this.stopPolling();}
    startPolling(){this.stopPolling();this.poller=window.setInterval(async()=>{try{await this.refresh(false);}catch(_){/* retry next poll */}},3000);}
    stopPolling(){if(this.poller){window.clearInterval(this.poller);this.poller=null;}}
    async refresh(showBusy=true){if(showBusy)this.busy=true;try{const requestedRunId=this.activeRunId;const [status,jobs,sourceTypes,history]=await Promise.all([getStatus({runId:requestedRunId}),getScheduledJobs(),getSourceTypes(),getRecentRuns({rowLimit:10})]);const returnedRun=status?.run||null;const returnedRunning=['Queued','Running','Holding','Preparing','Processing'].includes(this.field(returnedRun,'Status__c'));if(requestedRunId&&returnedRun&&!returnedRunning){this.activeRunId=null;const latest=await getStatus({runId:null});this.status=latest;this.schedules=(latest?.schedules||[]).map(r=>({...r,_key:r.Id||`new-${++this.scheduleSeq}`}));}else{this.status=status;this.schedules=(status?.schedules||[]).map(r=>({...r,_key:r.Id||`new-${++this.scheduleSeq}`}));}this.updateDisplayedProgress();this.jobs=jobs||[];this.sourceTypes=sourceTypes||[];this.history=(history||[]).slice(0,10);if(showBusy)this.message='';}catch(e){this.message=this.errorText(e,'Unable to load Field Usage operations.');}finally{if(showBusy)this.busy=false;}}
    async handleRunNow(){if(this.scanRunning)return;this.busy=true;this.message='Starting Field Usage scan...';this.displayedProgress=0;this.progressRunId=null;this.status={...(this.status||{}),run:{Status__c:'Queued',Progress_Percent__c:0,Progress_Phase__c:'Waiting for background scan to start',Objects_Processed__c:0,Objects_Total__c:0,Dependency_Count__c:0,Error_Count__c:0}};try{const runId=await runNow();this.activeRunId=runId;this.message='Field Usage scan queued.';this.startPolling();await this.refresh(false);}catch(e){this.message=this.errorText(e,'Unable to start Field Usage scan.');this.activeRunId=null;await this.refresh(false);}finally{this.busy=false;}}
    async handleHistoryToggle(e){const id=e.currentTarget.dataset.id;if(this.expandedRunId===id){this.expandedRunId=null;return;}this.expandedRunId=id;if(this.errorDetails[id])return;this.errorLoadingId=id;try{const detail=await getErrorDetail({runId:id});this.errorDetails={...this.errorDetails,[id]:detail};}catch(err){this.errorDetails={...this.errorDetails,[id]:{errors:this.errorText(err,'Unable to load persisted scan error detail.')}};}finally{this.errorLoadingId=null;}}
    handleAddSchedule(){this.schedules=[...this.schedules,{_key:`new-${++this.scheduleSeq}`,Name:'Field Usage Schedule',Enabled__c:true,Hour__c:3,Minute__c:0}];}
    changeSchedule(key,patch){this.schedules=this.schedules.map(r=>r._key===key?{...r,...patch}:r);}
    handleName(e){this.changeSchedule(e.currentTarget.dataset.key,{Name:e.target.value});} handleEnabled(e){this.changeSchedule(e.currentTarget.dataset.key,{Enabled__c:e.target.checked});} handleHour(e){this.changeSchedule(e.currentTarget.dataset.key,{Hour__c:Number(e.target.value)});} handleMinute(e){this.changeSchedule(e.currentTarget.dataset.key,{Minute__c:Number(e.target.value)});}
    async handleSaveSchedules(){this.busy=true;try{const rows=this.schedules.map(r=>({Id:r.Id,Name:r.Name||'Field Usage Schedule',Enabled__c:!!r.Enabled__c,Hour__c:Number(r.Hour__c),Minute__c:Number(r.Minute__c)}));await saveSchedules({rows});this.message='Automatic scan schedules saved.';await this.refresh(false);}catch(e){this.message=this.errorText(e,'Unable to save schedules.');}finally{this.busy=false;}}
    async handleDeleteSchedule(e){const key=e.currentTarget.dataset.key,row=this.schedules.find(r=>r._key===key);this.busy=true;try{if(row?.Id)await deleteSchedule({scheduleId:row.Id});this.schedules=this.schedules.filter(r=>r._key!==key);this.message='Schedule deleted.';await this.refresh(false);}catch(err){this.message=this.errorText(err,'Unable to delete schedule.');}finally{this.busy=false;}}
    async handlePause(e){await this.jobAction(pauseSchedule,e.currentTarget.dataset.id,'Schedule paused.');} async handleResume(e){await this.jobAction(resumeSchedule,e.currentTarget.dataset.id,'Schedule resumed.');} async handleDeleteJob(e){await this.jobAction(deleteSchedule,e.currentTarget.dataset.id,'Schedule deleted.');}
    async jobAction(fn,id,success){this.busy=true;try{await fn({scheduleId:id});this.message=success;await this.refresh(false);}catch(e){this.message=this.errorText(e,'Unable to update scheduled job.');}finally{this.busy=false;}}
    errorText(e,fallback){const body=e?.body;if(typeof body==='string'&&body.trim())return body;if(body?.message)return body.message;const pageErrors=body?.pageErrors||body?.output?.errors;if(Array.isArray(pageErrors)&&pageErrors.length){const messages=pageErrors.map(x=>x?.message||String(x)).filter(Boolean);if(messages.length)return messages.join(' | ');}const fieldErrors=body?.fieldErrors||body?.output?.fieldErrors;if(fieldErrors&&typeof fieldErrors==='object'){const messages=Object.values(fieldErrors).flat().map(x=>x?.message||String(x)).filter(Boolean);if(messages.length)return messages.join(' | ');}if(Array.isArray(body)){const messages=body.map(x=>x?.message||x?.errorCode||String(x)).filter(Boolean);if(messages.length)return messages.join(' | ');}if(e?.message)return e.message;try{const serialised=JSON.stringify(body||e);if(serialised&&serialised!=='{}')return serialised;}catch(_){/* use fallback */}return fallback;}
    field(row,apiName){if(!row)return undefined;if(Object.prototype.hasOwnProperty.call(row,apiName))return row[apiName];const key=Object.keys(row).find(k=>k.endsWith(apiName));return key?row[key]:undefined;}
    get run(){return this.status?.run||null;}
    get runStatus(){return this.field(this.run,'Status__c')||'Not scanned';}
    get scanRunning(){return ['Queued','Running','Holding','Preparing','Processing'].includes(this.runStatus);}
    get snapshotState(){return this.field(this.run,'Is_Current__c')&&this.runStatus==='Completed'?'Current':this.runStatus;}
    get healthState(){return this.scanRunning?'Processing':(Number(this.field(this.run,'Error_Count__c')||0)>0?'Attention':(this.field(this.run,'Is_Current__c')?'Healthy':'Not scanned'));}
    get dependencyCount(){return Number(this.field(this.run,'Dependency_Count__c')||0);} get objectsProcessed(){return Number(this.field(this.run,'Objects_Processed__c')||0);} get objectsTotal(){return Number(this.field(this.run,'Objects_Total__c')||0);} get progressLog(){return this.field(this.run,'Progress_Log__c')||'';} get hasProgressLog(){return !!this.progressLog;} get errorCount(){return Number(this.field(this.run,'Error_Count__c')||0);} get jobTotal(){return Number(this.status?.jobTotal||0);} get jobProcessed(){return Number(this.status?.jobProcessed||0);} get jobErrors(){return Number(this.status?.jobErrors||0);} get jobStatus(){return this.status?.jobStatus||'';}
    updateDisplayedProgress(){const runId=this.run?.Id||this.activeRunId||null;if(runId!==this.progressRunId){this.progressRunId=runId;this.displayedProgress=0;}const persisted=Math.max(0,Math.min(this.scanRunning?99:100,Number(this.field(this.run,'Progress_Percent__c')||0)));let candidate=!this.scanRunning&&/Completed/i.test(this.runStatus)?100:persisted;const phase=String(this.field(this.run,'Progress_Phase__c')||'');if(this.scanRunning&&persisted<=1&&/Discovering scan work/i.test(phase)&&this.jobTotal>0){const discoveryFraction=Math.max(0,Math.min(1,this.jobProcessed/this.jobTotal));candidate=Math.max(candidate,1+Math.floor(discoveryFraction*3));}this.displayedProgress=Math.max(this.displayedProgress,candidate);}
    get progress(){return Math.max(0,Math.min(100,Number(this.displayedProgress||0)));}
    get progressStyle(){return `width:${this.progress}%;`;}
    get phase(){const persisted=this.field(this.run,'Progress_Phase__c');if(persisted)return persisted;if(this.scanRunning)return this.jobStatus?`Pipeline running · current batch ${this.jobStatus}`:'Pipeline running';return 'Idle';}
    get lastCompleted(){return this.formatDate(this.field(this.run,'Completed_At__c'));} get hasJobs(){return this.jobs.length>0;} get hasSchedules(){return this.schedules.length>0;} get hasHistory(){return this.history.length>0;}
    get jobsView(){return this.jobs.map(j=>({...j,key:j.scheduleId||j.cronTriggerId||j.jobName,next:this.formatDate(j.nextFireTime),previous:this.formatDate(j.previousFireTime),state:j.state||(j.enabled?'Scheduled':'Paused'),time:`${String(Math.trunc(Number(j.hour||0))).padStart(2,'0')}:${String(Math.trunc(Number(j.minute||0))).padStart(2,'0')}`,canPause:!!j.enabled,canResume:!j.enabled}));}
    get historyView(){return this.history.slice(0,10).map((r,index)=>{const id=r.Id||`run-${index}`;const status=this.field(r,'Status__c')||'Unknown';const errors=Number(this.field(r,'Error_Count__c')||0);const phase=this.field(r,'Progress_Phase__c')||'—';const hasError=errors>0||/error|fail/i.test(status);const detail=this.errorDetails[id];const loading=this.errorLoadingId===id;let errorDetail='';if(loading)errorDetail='Loading persisted error detail…';else if(detail){const primary=detail.errors||'No persisted Errors__c detail was recorded for this run.';const context=detail.progressLog?`\n\nProgress log:\n${detail.progressLog}`:'';const objects=detail.objectsTotal?`\n\nObjects processed: ${detail.objectsProcessed} / ${detail.objectsTotal}`:'';errorDetail=`${primary}${context}${objects}`;}return {key:id,id,number:index+1,status,started:this.formatDate(this.field(r,'Started_At__c')),completed:this.formatDate(this.field(r,'Completed_At__c')),dependencies:Number(this.field(r,'Dependency_Count__c')||0),errors,phase,hasError,errorDetail,isExpanded:this.expandedRunId===id,toggleLabel:this.expandedRunId===id?'Hide error':'View error'};});}
    get coverageRows(){return this.sourceTypes.map((name,i)=>({key:`coverage-${i}`,name,status:'Operational'}));}
    formatDate(v){if(!v)return '—';try{return new Date(v).toLocaleString();}catch(_){return String(v);}}
}